In [2]:
using Pkg
Pkg.add("Colors")
using Colors

    Updating registry at `C:\Users\17404\.julia\registries\General.toml`
   Resolving package versions...
  No Changes to `C:\Users\17404\.julia\environments\v1.7\Project.toml`
  No Changes to `C:\Users\17404\.julia\environments\v1.7\Manifest.toml`


In [1]:
x = 9 #number of rows
y = 9 #number of columns
A = rand(0:1,x,y) #a random martix represent counters by positions

9×9 Matrix{Int64}:
 1  1  0  0  1  1  1  1  0
 1  0  0  0  0  0  1  1  0
 1  1  1  0  0  1  0  0  0
 1  1  0  1  0  0  0  1  1
 1  1  0  1  1  0  1  0  0
 1  0  0  1  0  1  0  1  0
 1  0  1  0  0  1  0  1  1
 1  0  1  0  0  1  0  1  0
 0  0  1  0  0  0  1  0  1

In [3]:
function num2col(i)
    if i == 1
        return colorant"black"
    elseif i == 0
        return colorant"white"
    end
end

num2col (generic function with 1 method)

In [4]:
num2col.(A)

In [5]:
B = zeros(Int64, x+2, y+2) #create an empty martix with one more layer of zeros

11×11 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0

In [6]:
#move the original random martix into this bigger one
for i in 1:x, j in 1:y
    B[i+1,j+1] = A[i,j]# every counter go 1 down and 1 rifht forward.
end
B

11×11 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0  0
 0  1  1  0  0  1  1  1  1  0  0
 0  1  0  0  0  0  0  1  1  0  0
 0  1  1  1  0  0  1  0  0  0  0
 0  1  1  0  1  0  0  0  1  1  0
 0  1  1  0  1  1  0  1  0  0  0
 0  1  0  0  1  0  1  0  1  0  0
 0  1  0  1  0  0  1  0  1  1  0
 0  1  0  1  0  0  1  0  1  0  0
 0  0  0  1  0  0  0  1  0  1  0
 0  0  0  0  0  0  0  0  0  0  0

In [7]:
N = zeros(Int64, x, y) #create an empty number of corresponding neighbors martix

9×9 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0

In [8]:
#generate the number of corresponding neighbors
for i in 1:x, j in 1:y
    N[i,j]= B[i,j]+B[i,j+1]+B[i,j+2]+B[i+1,j]+B[i+1,j+2]+B[i+2,j]+B[i+2,j+1]+B[i+2,j+2]# Sum the surrounding neighbors up bu locations
end
N

9×9 Matrix{Int64}:
 2  2  1  1  1  3  4  3  2
 4  6  3  2  3  5  5  3  2
 4  5  3  2  2  1  4  4  3
 5  6  6  3  4  3  3  2  1
 4  4  5  3  4  3  3  4  3
 3  5  4  3  5  3  5  3  3
 2  5  2  3  4  2  6  3  3
 1  5  2  3  2  2  5  4  4
 1  3  1  2  1  2  2  3  1

In [9]:
#run the three laws of life
for i in 1:x, j in 1:y
    #survival law:
    if A[i,j] == 1
        if N[i,j] == 2 || N[i,j] == 3# if there are 2 or 3 neighbors
            A[i,j] = 1# then this counter remain alive
        #death law:
        elseif N[i,j] >= 4 || N[i,j] <= 1# if there are greater than or equal to 4, or less than or euqal to 1 neighbors
            A[i,j] = 0# then this counter die
        end
    else
        #birth law:
        if N[i,j] == 3# if this counter have exacut 3 neighbors
            A[i,j] = 1# then generate a new one in this box
        end
    end
end
A

9×9 Matrix{Int64}:
 1  1  0  0  0  1  0  1  0
 0  0  1  0  1  0  0  1  0
 0  0  1  0  0  0  0  0  1
 0  0  0  1  0  1  1  1  0
 0  0  0  1  0  1  1  0  1
 1  0  0  1  0  1  0  1  1
 1  0  1  1  0  1  0  1  1
 0  0  1  1  0  1  0  0  0
 0  1  0  0  0  0  1  1  0

In [10]:
num2col.(A)

In [11]:
#make a function of generate next martix based on pervious one
function runlaws(A)
    for i in 1:x, j in 1:y
        B[i+1,j+1] = A[i,j]
    end
    N = zeros(Int64, x, y) #create an empty number of corresponding neighbors martix
    #generate the number of corresponding neighbors
    for i in 1:x, j in 1:y
        N[i,j]= B[i,j]+B[i,j+1]+B[i,j+2]+B[i+1,j]+B[i+1,j+2]+B[i+2,j]+B[i+2,j+1]+B[i+2,j+2]
    end
    #run the three laws of life
    for i in 1:x, j in 1:y
        #survival
        if A[i,j] == 1
            if N[i,j] == 2 || N[i,j] == 3
                A[i,j] = 1
            #death
            elseif N[i,j] >= 4 || N[i,j] <= 1
                A[i,j] = 0
            end
        else
            #birth
            if N[i,j] == 3
                A[i,j] = 1
            end
        end
    end
    return A
end

runlaws (generic function with 1 method)

In [12]:
#run this fucntion
runlaws(A)

9×9 Matrix{Int64}:
 0  1  0  0  0  0  1  0  0
 0  0  1  1  0  0  1  1  1
 0  0  1  0  1  1  0  0  1
 0  0  1  1  0  1  0  0  1
 0  0  1  1  0  0  0  0  1
 0  1  0  1  0  1  0  0  0
 0  0  0  0  0  1  0  1  1
 0  0  0  1  0  1  0  0  1
 0  0  1  0  0  0  1  0  0

In [13]:
#show the graph of the third generation
num2col.(A)

In [14]:
#run this fucntion
runlaws(A)

9×9 Matrix{Int64}:
 0  0  1  0  0  0  1  0  0
 0  1  1  1  1  0  1  0  1
 0  1  0  0  0  1  0  0  1
 0  1  0  0  0  1  0  1  1
 0  1  0  0  0  0  0  0  0
 0  0  0  1  0  0  1  1  1
 0  0  1  0  0  1  0  1  1
 0  0  0  0  1  1  0  0  1
 0  0  0  0  0  0  0  0  0

In [15]:
#show the graph of the fourth generation
num2col.(A)

In [16]:
#run this fucntion
runlaws(A)

9×9 Matrix{Int64}:
 0  1  1  0  0  1  0  1  0
 0  1  0  1  1  0  1  0  0
 1  1  0  1  0  1  0  0  1
 1  1  1  0  0  0  1  1  1
 0  0  1  0  0  0  0  0  0
 0  0  1  0  0  0  1  0  1
 0  0  0  1  0  1  0  0  0
 0  0  0  0  1  1  1  1  1
 0  0  0  0  0  0  0  0  0

In [17]:
#show the graph of the fifrth generation
num2col.(A)

In [18]:
#run this fucntion
runlaws(A)

9×9 Matrix{Int64}:
 0  1  1  1  1  1  1  0  0
 0  0  0  1  0  0  1  1  0
 0  0  0  1  0  1  0  0  1
 1  0  0  1  0  0  1  1  1
 0  0  1  1  0  0  1  0  1
 0  0  1  1  0  0  0  0  0
 0  0  0  1  0  0  0  0  1
 0  0  0  0  1  1  1  1  0
 0  0  0  0  0  1  1  1  0

In [19]:
#show the graph of the sixth generation
num2col.(A)

In [20]:
#run this fucntion
runlaws(A)

9×9 Matrix{Int64}:
 0  0  1  1  1  1  1  1  0
 0  0  0  0  0  0  0  1  0
 0  0  1  1  0  1  0  0  1
 0  0  0  1  0  1  1  0  1
 0  1  0  0  1  0  1  0  1
 0  0  0  0  1  0  0  1  0
 0  0  1  1  0  1  1  1  0
 0  0  0  0  1  0  0  0  1
 0  0  0  0  1  0  0  1  0

In [21]:
#show the graph of the sixth generation
num2col.(A)

In [22]:
#run this fucntion
runlaws(A)

9×9 Matrix{Int64}:
 0  0  0  1  1  1  1  1  0
 0  0  0  0  0  0  0  1  1
 0  0  1  1  0  1  0  0  1
 0  0  0  1  0  0  1  0  1
 0  0  0  1  1  0  1  0  1
 0  0  1  0  1  0  0  0  1
 0  0  0  1  0  1  1  1  1
 0  0  0  0  1  0  0  0  1
 0  0  0  0  0  0  0  0  0

In [23]:
#show the graph of the sixth generation
num2col.(A)

In [24]:
#run this fucntion
runlaws(A)

9×9 Matrix{Int64}:
 0  0  0  0  1  1  1  1  1
 0  0  1  0  0  0  0  0  1
 0  0  1  1  1  0  1  0  1
 0  0  0  0  0  0  1  0  1
 0  0  1  0  1  0  0  0  1
 0  0  1  0  0  0  0  0  1
 0  0  0  1  0  1  1  0  1
 0  0  0  0  1  1  1  0  1
 0  0  0  0  0  0  0  0  0

In [25]:
#show the graph of the sixth generation
num2col.(A)

In [26]:
#run this fucntion
runlaws(A)

9×9 Matrix{Int64}:
 0  0  0  0  0  1  1  1  1
 0  0  1  0  0  0  0  0  1
 0  0  1  1  0  1  0  0  1
 0  0  1  0  1  0  0  0  1
 0  0  0  1  0  0  0  0  1
 0  0  1  0  1  1  0  0  1
 0  0  0  1  0  0  1  0  1
 0  0  0  0  1  0  1  0  0
 0  0  0  0  0  1  0  0  0

In [27]:
#show the graph of the sixth generation
num2col.(A)

In [28]:
#run this fucntion
runlaws(A)

9×9 Matrix{Int64}:
 0  0  0  0  0  0  1  1  1
 0  0  1  1  1  1  0  0  1
 0  1  1  0  1  0  0  1  1
 0  0  1  0  1  0  0  1  1
 0  0  1  0  0  1  0  1  1
 0  0  1  0  1  1  0  0  1
 0  0  0  1  0  0  1  0  0
 0  0  0  0  1  0  1  1  0
 0  0  0  0  0  1  0  0  0

In [29]:
#show the graph of the sixth generation
num2col.(A)

In [30]:
#run this fucntion
runlaws(A)

9×9 Matrix{Int64}:
 0  0  0  1  1  1  1  1  1
 0  1  1  0  1  1  0  0  0
 0  1  0  0  0  0  1  0  0
 0  0  1  0  1  1  0  0  0
 0  1  1  0  0  1  0  0  0
 0  0  1  0  1  1  0  0  1
 0  0  0  1  0  0  1  0  0
 0  0  0  0  1  0  1  1  0
 0  0  0  0  0  1  1  0  0

In [31]:
#show the graph of the sixth generation
num2col.(A)